### ISSUE TITLE
"engines" section does not automatically update the npm version

### ISSUE THREAD

**Issue by ryanj** [ryanj/nodejs-custom-version-openshift#1]
Lee (@LeeFernandes / @ItsLeeOwen) left a review with some good feedback here: https://hub.openshift.com/quickstarts/128-node-js-0-12 

> I've added the "engines" config to package.json, but dependencies are failing reporting outdated node/npm versions.

```
wanted: {"node":">= 0.12.0","npm":">= 1.4.0"} (current: {"node":"v0.10.25","npm":"1.3.24"})
```

This is by design.  The "engines" section isn't normally used to install anything.  This quickstart includes a bundle of code inside the `.openshift` folder that will automatically read the "engines" section in order to install recent versions of nodejs.  However, I didn't include any code to update the `npm` version since that functionality is already covered by the `package.json` file's `dependencies` section.

If you want to use a specific version of `npm`, make sure to include that information in your `package.json` file by running `npm install npm --save`.

I've update the hub page and the project README in order to help clarify.
Thanks for sending your feedback!

**Comment by ghost** [comment]
Gotcha, sorry about the crap openshift hub review, I need to update it somehow.

**Comment by ryanj** [comment]
np!  thanks for leaving feedback. :)

Is it okay if we clear the old review for you?  Feel free to resubmit

**Comment by ghost** [comment]
yes thanks

On Mon, Apr 6, 2015 at 4:03 PM, ryan jarvinen notifications@github.com
wrote:

> np! thanks for leaving feedback. :)
> 
> Is it okay if we clear the old review for you? Feel free to resubmit
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ryanj/nodejs-custom-version-openshift/issues/1#issuecomment-90224925
> .

## 

[image: Laicos] http://laicos.com/ _Lee Fernandes yyang@laicos.com_ Full
Stack Developer1000 N Ashley Dr | Suite 520 | Tampa, FL 33602
https://goo.gl/maps/KWhICLaicos.com http://laicos.com/ | (941) 254-1998
<+1-727-475-0838>[image: Twitter] http://twitter.com/laicos/ [image:
Facebook] http://facebook.com/laicosllc/ [image: Google+]
https://plus.google.com/u/0/b/112692347994913959390/112692347994913959390
[image:
LinkedIn] https://www.linkedin.com/company/3279311 [image: Blog]
http://laicos.com/blog/

**Comment by luciddreamz** [comment]
@leefernandes Your review has been removed (with permission obviously). Feel free to submit a new review: https://hub.openshift.com/quickstarts/128-node-js-0-12

Also, I made a note to add a feature allowing users to delete their own reviews on OpenShift Hub. We'll also try to link to GitHub issues where appropriate :)
