### ISSUE TITLE
Fails to create application

### ISSUE THREAD

**Issue by Tobbe** [ryanj/nodejs-custom-version-openshift#4]
Running `rhc app create twitter_proxy --from-code=git://github.com/ryanj/nodejs-custom-version-openshift.git` I get 

> Every application needs a web cartridge to handle incoming web requests. Please provide the short name of one of the carts listed above."

And then the script exits.

**Comment by prestonvanloon** [comment]
You forgot to add the nodejs bit. 

`rhc app create twitter_proxy nodejs --from-code=git://github.com/ryanj/nodejs-custom-version-openshift.git`

**Comment by Tobbe** [comment]
Ahh, yes, thanks :)
