### ISSUE TITLE
What's with the index.html and server.js stuff? Isn't this for my app, and not yours?

### ISSUE THREAD

**Issue by balupton** [ryanj/nodejs-custom-version-openshift#5]

**Comment by skcc75** [comment]
That's just an example.  Feel free to replace them.

**Comment by ryanj** [comment]
This was just an example to show folks how to install or update nodejs by adding some hacks to their application source.  Ideally, the Nodejs runtime should be provided by the platform, or by a "cartridge".

Now that it's available, I'd recommend trying this cart instead: https://hub.openshift.com/quickstarts/243-node-js-latest

It can be used with your own repo.
